<?php
$machineNames = array(
	'Лущение',
	'Ножницы',
	'Котельная',
	'Сушилка',
	'Опиловка',
	'Шлифовка',
	'Сращивание',
	'Распиловка',
	'Пресс',
	'Раскряжёвка',
	'Ребросклейка'
);

$plotVariants = array(
	array( // 0. raute_shell
		array( // 0
			'title' => 'Производительность',
			'machine' => 'raute_shell',
			'field' => array('curr_vol'),
			'operation' => 'powerFromValue',
			'valueScale' => 1000000000, // делитель для пересчёта объёма из мм^3 в м^3
			'valueDailyScale' => 100, // множитель для пересчёта показателя при использовании обобщённых дневных данных
			'units' => ' м<sup>3</sup>/час',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 1
			'title' => 'Объём поданного кряжа',
			'machine' => 'raute_shell',
			'field' => array('curr_vol'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 2
			'title' => '% выхода лущения',
			'machine' => 'raute_shell',
			//'field' => array('curr_vol', 'percent_exit'),
			'field' => array('percent_exit'),
			//'operation' => 'avg_percent',
			'operation' => 'avg',
			'valueScale' => 10,
			'valueDailyScale' => 1,
			'units' => '%',
			'yAxisMin' => 40,
			'yAxisFormat' => '%.1f'
		),
		array( // 3
			'title' => '% на карандаш',
			'machine' => 'raute_shell',
			'field' => array('percent_core'),
			'operation' => 'avg_notzero',
			'valueScale' => 10,
			'valueDailyScale' => 1,
			'units' => '%',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 4
			'title' => 'Объём карандаша',
			'machine' => 'raute_shell',
			'field' => array('core_vol'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 5
			'title' => 'Средний диаметр чурака',
			'machine' => 'raute_shell',
			'field' => array('r_init'),
			'operation' => 'avg_diameter',
			'valueScale' => 10,
			'valueDailyScale' => 1,
			'units' => ' см',
			'yAxisMin' => 15,
			'yAxisFormat' => '%.2f'
		),
		array( // 6
			'title' => 'Средний диаметр карандаша',
			'machine' => 'raute_shell',
			'field' => array('r_core'),
			'operation' => 'avg_diameter',
			'valueScale' => 10,
			'valueDailyScale' => 1,
			'units' => ' см',
			'yAxisMin' => 1,
			'yAxisFormat' => '%.2f'
		),
		array( // 7
			'title' => 'Количество чураков',
			'machine' => 'raute_shell',
			'field' => array('id'),
			'operation' => 'count',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 8
			'title' => 'Суммарный выход с ножниц',
			'machine' => 'raute_cutter',
			'field' => array('bin1_incr', 'bin2_incr', 'bin3_incr'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 9
			'title' => 'Открытие ножевой щели',
			'machine' => 'raute_shell',
			'field' => array('knife_position'),
			'operation' => 'exactVals',
			'valueScale' => 100,
			'valueDailyScale' => 100,
			'units' => ' мм',
			'yAxisMin' => 1.2,
			'yAxisFormat' => '%.2f'
		),
		array( // 10
			'title' => 'Толщина шпона',
			'machine' => 'raute_cutter',
			'field' => array('thickness'),
			'operation' => 'exactVals',
			'valueScale' => 100,
			'valueDailyScale' => 100,
			'units' => ' мм',
			'yAxisMin' => 1.4,
			'yAxisFormat' => '%.2f'
		),
		
	),
	array( // 1. raute_cutter
		array( // 0
			'title' => 'Производительность',
			'machine' => 'raute_cutter',
			'field' => array('bin1_incr', 'bin2_incr', 'bin3_incr'),
			'operation' => 'powerFromValue',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 1
			'title' => 'Прирост объёма на столе 1',
			'machine' => 'raute_cutter',
			'field' => array('bin1_incr'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 2
			'title' => 'Прирост объёма на столе 2',
			'machine' => 'raute_cutter',
			'field' => array('bin2_incr'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 3
			'title' => 'Прирост объёма на столе 3',
			'machine' => 'raute_cutter',
			'field' => array('bin3_incr'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 4
			'title' => 'Суммарный объём',
			'machine' => 'raute_cutter',
			'field' => array('bin1_incr', 'bin2_incr', 'bin3_incr'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
	),
	array( // 2. boiler
		array( // 0
			'title' => 'Заданная температура',
			'machine' => 'boiler',
			'field' => array('temp_specified'),
			'operation' => 'exactVals',
			'valueScale' => 10,
			'valueDailyScale' => 1,
			'units' => '°С',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 1
			'title' => 'Прямая температура',
			'machine' => 'boiler',
			'field' => array('temp_send'),
			'operation' => 'avg',
			'valueScale' => 10,
			'valueDailyScale' => 1,
			'units' => '°С',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 2
			'title' => 'Обратная температура',
			'machine' => 'boiler',
			'field' => array('temp_receive'),
			'operation' => 'avg',
			'valueScale' => 10,
			'valueDailyScale' => 1,
			'units' => '°С',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 3
			'title' => 'Мощность',
			'machine' => 'boiler',
			'field' => array('power'),
			'operation' => 'avg',
			'valueScale' => 10,
			'valueDailyScale' => 1,
			'units' => '%',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		)
	),
	array( // 3. warmer
		array( // 0
			'title' => 'Производительность',
			'machine' => 'warmer',
			'field' => array('totalSq'),
			'operation' => 'powerFromSquare',
			'valueScale' => 100,
			'valueDailyScale' => 1,
			'units' => ' м<sup>3</sup>/час',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 1
			'title' => 'Подано партий в минуту',
			'machine' => 'warmer',
			'field' => array('packages'),
			'operation' => 'avg',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' парт/мин',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 2
			'title' => 'Скорость внутри сушилки',
			'machine' => 'warmer',
			'field' => array('velocity'),
			'operation' => 'avg_notzero',
			'valueScale' => 16.66667,
			'valueDailyScale' => 1,
			'units' => ' м/мин',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 3
			'title' => 'Подано красного шпона',
			'machine' => 'warmer',
			'field' => array('redSquare'),
			'operation' => 'valueFromSquare',
			'valueScale' => 100,
			'valueDailyScale' => 10,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 4
			'title' => 'Подано сырого шпона',
			'machine' => 'warmer',
			'field' => array('totalSq'),
			'operation' => 'valueFromSquare',
			'valueScale' => 100,
			'valueDailyScale' => 10,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 5
			'title' => 'Выход сухого шпона',
			'machine' => 'warmer_out',
			'field' => array('usefull_square', 'merger_square'), // , 'useless_square'
			'operation' => 'valueFromSquare',
			'valueScale' => 100,
			'valueDailyScale' => 10,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 6
			'title' => 'Объём целых листов',
			'machine' => 'warmer_out',
			'field' => array('usefull_square'),
			'operation' => 'valueFromSquare',
			'valueScale' => 100,
			'valueDailyScale' => 10,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 7
			'title' => 'Объём листов для сращивания',
			'machine' => 'warmer_out',
			'field' => array('merger_square'),
			'operation' => 'valueFromSquare',
			'valueScale' => 100,
			'valueDailyScale' => 10,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 8
			'title' => 'Объём отходов',
			'machine' => 'warmer_out',
			'field' => array('useless_square'),
			'operation' => 'valueFromSquare',
			'valueScale' => 100,
			'valueDailyScale' => 10,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 9
			'title' => 'Число задействованных полок',
			'machine' => 'warmer',
			'field' => array('shelves'),
			'operation' => 'exactVals',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 10
			'title' => 'Число длинных листов',
			'machine' => 'warmer_out',
			'field' => array('usefull_quant'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 11
			'title' => 'Число коротких листов',
			'machine' => 'warmer_out',
			'field' => array('merger_quant'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
	),
	array( // 4. lopping
		array( // 0
			'title' => 'Производительность',
			'machine' => 'lopping',
			'field' => array('value'),
			'operation' => 'powerFromValue',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>/час',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 1
			'title' => 'Объём опиленных листов',
			'machine' => 'lopping',
			'field' => array('value'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 2
			'title' => 'Количество опиленных листов',
			'machine' => 'lopping',
			'field' => array('part_id'),
			'operation' => 'count',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => 'шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 3
			'title' => 'Заданная толщина',
			'machine' => 'lopping',
			'field' => array('thickness'),
			'operation' => 'asIs',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
			'maxLength' => 60 * 60 * 24
		),
		array( // 4
			'title' => 'Скорость 1-й опиловки',
			'machine' => 'lopping',
			'field' => array('velocity_long'),
			'operation' => 'avg',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' м/мин',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 5
			'title' => 'Скорость 2-й опиловки',
			'machine' => 'lopping',
			'field' => array('velocity_short'),
			'operation' => 'avg',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' м/мин',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 6
			'title' => 'В среднем листов в минуту',
			'machine' => 'lopping',
			'field' => array('part_id'),
			'operation' => 'piecesPerMinute',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт/мин',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
	),
	array( // 5. grinding
		array( // 0
			'title' => 'Производительность',
			'machine' => 'grinding',
			'field' => array('value_bin1', 'value_bin2', 'value_bin3'),
			'operation' => 'powerFromValue',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>/час',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 1
			'title' => 'Объём листов на столе 1',
			'machine' => 'grinding',
			'field' => array('value_bin1'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 2
			'title' => 'Объём листов на столе 2',
			'machine' => 'grinding',
			'field' => array('value_bin2'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 3
			'title' => 'Объём листов на столе 3',
			'machine' => 'grinding',
			'field' => array('value_bin3'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 4
			'title' => 'Скорость шлифовки',
			'machine' => 'grinding',
			'field' => array('velocity'),
			'operation' => 'avg',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' м/мин',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 5
			'title' => 'Количество поданных листов',
			'machine' => 'grinding',
			'field' => array('part_id'),
			'operation' => 'count',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 6
			'title' => 'Заданная толщина',
			'machine' => 'grinding',
			'field' => array('thickness'),
			'operation' => 'asIs',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
			'maxLength' => 60 * 60 * 24
		),
		array( // 7
			'title' => 'Суммарный объём',
			'machine' => 'grinding',
			'field' => array('value_bin1', 'value_bin2', 'value_bin3'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
	),
	array( // 6. merger
		array( // 0
			'title' => 'Производительность (нов)',
			'machine' => 'merger',
			'field' => array('merg_total_value'),
			'operation' => 'powerFromValue',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>/час',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 1
			'title' => 'Производительность (стар)',
			'machine' => 'merger_old',
			'field' => array('merg_total_value'),
			'operation' => 'powerFromValue',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>/час',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 2
			'title' => 'Объём (новая линия)',
			'machine' => 'merger',
			'field' => array('merg_total_value'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 3
			'title' => 'Объём с пресса 1',
			'machine' => 'merger',
			'field' => array('press1_merg_value'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 4
			'title' => 'Объём с пресса 2',
			'machine' => 'merger',
			'field' => array('press2_merg_value'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 5
			'title' => 'Объём с пресса 3',
			'machine' => 'merger',
			'field' => array('press3_merg_value'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 6
			'title' => 'Всего сращиваний',
			'machine' => 'merger',
			'field' => array('press1_merg_count', 'press2_merg_count', 'press3_merg_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 7
			'title' => 'Число листов на усовке',
			'machine' => 'merger',
			'field' => array('count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 8
			'title' => 'Длина опиловки',
			'machine' => 'merger',
			'field' => array('length'),
			'operation' => 'exactVals',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 9
			'title' => 'Ширина опиловки',
			'machine' => 'merger',
			'field' => array('width'),
			'operation' => 'exactVals',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 10
			'title' => 'Число сращиваний на прессе 1',
			'machine' => 'merger',
			'field' => array('press1_merg_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 11
			'title' => 'Число сращиваний на прессе 2',
			'machine' => 'merger',
			'field' => array('press2_merg_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 12
			'title' => 'Число сращиваний на прессе 3',
			'machine' => 'merger',
			'field' => array('press3_merg_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		
		
		array( // 13
			'title' => 'Объём (старая линия)',
			'machine' => 'merger_old',
			'field' => array('merg_total_value'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 14
			'title' => 'Объём с пресса 1 (ст.)',
			'machine' => 'merger_old',
			'field' => array('press1_merg_value'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 15
			'title' => 'Объём с пресса 2 (ст.)',
			'machine' => 'merger_old',
			'field' => array('press2_merg_value'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 16
			'title' => 'Объём с пресса 3 (ст.)',
			'machine' => 'merger_old',
			'field' => array('press3_merg_value'),
			'operation' => 'sum',
			'valueScale' => 1000000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 17
			'title' => 'Всего сращиваний (ст.)',
			'machine' => 'merger_old',
			'field' => array('press1_merg_count', 'press2_merg_count', 'press3_merg_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 18
			'title' => 'Число листов на усовке (ст.)',
			'machine' => 'merger_old',
			'field' => array('count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 19
			'title' => 'Длина опиловки (ст.)',
			'machine' => 'merger_old',
			'field' => array('length'),
			'operation' => 'exactVals',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 20
			'title' => 'Ширина опиловки (ст.)',
			'machine' => 'merger_old',
			'field' => array('width'),
			'operation' => 'exactVals',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 21
			'title' => 'Число сращиваний на прессе 1 (ст.)',
			'machine' => 'merger_old',
			'field' => array('press1_merg_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 22
			'title' => 'Число сращиваний на прессе 2 (ст.)',
			'machine' => 'merger_old',
			'field' => array('press2_merg_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 23
			'title' => 'Число сращиваний на прессе 3 (ст.)',
			'machine' => 'merger_old',
			'field' => array('press3_merg_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
	),
	array( // 7. saw
		array( // 0
			'title' => 'Подано стволов',
			'machine' => 'saw',
			'field' => array('tree_format'),
			'operation' => 'count',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 1
			'title' => 'Формат стволов',
			'machine' => 'saw',
			'field' => array('tree_format'),
			'operation' => 'exactVals',
			'valueScale' => 10,
			'valueDailyScale' => 10,
			'units' => ' м',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
	),
	array( // 8. press
		array( // 0
			'title' => 'Запресованный объём',
			'machine' => 'press',
			'field' => array('value'),
			'operation' => 'sum',
			'valueScale' => 100000000,
			'valueDailyScale' => 100,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f'
		),
		array( // 1
			'title' => 'Количество листов',
			'machine' => 'press',
			'field' => array('quant'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 2
			'title' => 'Давление',
			'machine' => 'press',
			'field' => array('pressure'),
			'operation' => 'asIs',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' бар',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f',
			'showLine' => false,
			'maxLength' => 60 * 60 * 3
		),
		array( // 3
			'title' => 'Время 1-й запрессовки',
			'machine' => 'press',
			'field' => array('time_1'),
			'operation' => 'exactVals',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' сек',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 4
			'title' => 'Время 2-й запрессовки',
			'machine' => 'press',
			'field' => array('time_2'),
			'operation' => 'exactVals',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' сек',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f'
		),
		array( // 5
			'title' => 'Толщина',
			'machine' => 'press',
			'field' => array('thickness'),
			'operation' => 'asIs',
			'valueScale' => 10,
			'valueDailyScale' => 10,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.1f',
			'showLine' => false,
			'maxLength' => 60 * 60 * 72
		),
	),
	array( // 9. saw_new
		array( // 0
			'title' => 'Количество стволов',
			'machine' => 'saw_new',
			'field' => array('init_length'),
			'operation' => 'countNotZero',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 1
			'title' => 'Длина ствола',
			'machine' => 'saw_new',
			'field' => array('init_length'),
			'operation' => 'asIs',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
			'showLine' => false,
			'maxLength' => 60 * 60 * 24
		),
		array( // 2
			'title' => 'Количество чураков',
			'machine' => 'saw_new',
			'field' => array('peeler_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
		),
		array( // 3
			'title' => 'Теоретически чураков',
			'machine' => 'saw_new',
			'field' => array('peeler_theory_count'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
		),
		array( // 4
			'title' => 'Длина чурака',
			'machine' => 'saw_new',
			'field' => array('peeler_length'),
			'operation' => 'asIs',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
		),
	),
	array( // 10. edge_gluing
		array( // 0
			'title' => 'Количество листов',
			'machine' => 'edge_gluing',
			'field' => array('merges'),
			'operation' => 'countNotZero',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f'
		),
		array( // 1
			'title' => 'Длина листа',
			'machine' => 'edge_gluing',
			'field' => array('length'),
			'operation' => 'asIs',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
			'showLine' => false
		),
		array( // 2
			'title' => 'Ширина листа',
			'machine' => 'edge_gluing',
			'field' => array('width'),
			'operation' => 'asIs',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' мм',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
			'showLine' => false
		),
		array( // 3
			'title' => 'Количество сращиваний',
			'machine' => 'edge_gluing',
			'field' => array('merges'),
			'operation' => 'sum',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
		),
		array( // 4
			'title' => 'Среднее число сращиваний на лист',
			'machine' => 'edge_gluing',
			'field' => array('merges'),
			'operation' => 'avg',
			'valueScale' => 1,
			'valueDailyScale' => 1,
			'units' => ' шт/лист',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.0f',
		),
		array( // 5
			'title' => 'Объём срощенных листов',
			'machine' => 'edge_gluing',
			'field' => array('square'),
			'operation' => 'valueFromSquare',
			'valueScale' => 1000,
			'valueDailyScale' => 1,
			'units' => ' м<sup>3</sup>',
			'yAxisMin' => 0,
			'yAxisFormat' => '%.2f',
		),
	)
);

?>